name: Build and Test

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash
    
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUILD_ENV: GitHub
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/fugro/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GLOBAL_READ_PACKAGES_SECRET}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal